### ISSUE TITLE
Question about rep_flow_layer.py

### ISSUE THREAD

**Issue by arunos728** [piergiaj/representation-flow-cvpr19#2]
Thanks for providing the great paper and code.
I found some differences between the paper and the code. (rep_flow_layer.py)
While implementing sobel filters for calculating (delta F, delta u), the code is written as 

self.img_grad = nn.Parameter(torch.FloatTensor([[[[-0.5,0,0.5]]]]).repeat(channels,1,1,1))
self.img_grad2 = nn.Parameter(torch.FloatTensor([[[[-0.5,0,0.5]]]]).transpose(3,2).repeat(channels,1,1,1))

self.f_grad = nn.Parameter(torch.FloatTensor([[[[-1,1]]]]).repeat(channels,1,1,1))
self.f_grad2 = nn.Parameter(torch.FloatTensor([[[[-1],[1]]]]).repeat(channels,1,1,1))

which is different from sobel filters in the paper.

Is there any reason for implementing sobel filters like this?

**Comment by piergiaj** [comment]
Thanks for pointing that out, I uploaded the wrong file. I will fix it soon.

In practice, the method of computing gradients doesn't have much effect, as long as it is actually computing the gradients.

**Comment by arunos728** [comment]
Thanks.
Here is another question, I found that skip connection is used for the architecture when calculating representation flow (flow_2p1d_resnets.py)

res = F.avg_pool3d(x,(3,1,1),1,0)#x[:,:,1:-1].contiguous()
...
x = x+res

In the paper, I saw that default setting is the non-fusion, so can I remove the two lines from the code?
