### ISSUE TITLE
How the set the "-learnable" argument

### ISSUE THREAD

**Issue by ziweizhao1993** [piergiaj/representation-flow-cvpr19#3]
Thanks for the code!

There's a "-learnable" argument with a comment "scale lr for flow layer", and a default value [0,0,0,0,0], did you change it during the experiments?

**Comment by piergiaj** [comment]
Yes, those control which parameters of the representation flow layer are learned. 2,3,4 are the hyperparameters (tau, alpha, lambda) and 0,1 determine if the sobel or divergence kernels are learned.

I found that [0,1,1,1,1] gave the best performance.
